# Generated by Django 3.0.7 on 2020-08-06 09:40

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VsUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.CharField(default='User', max_length=20)),
                ('Type', models.CharField(blank=True, max_length=200, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to=account.models.user_directory_path_favicon)),
                ('DOJ', models.DateField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('Contact_no', models.IntegerField(blank=True, default=0, null=True)),
                ('Zip_Code', models.IntegerField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=5, null=True)),
                ('password', models.CharField(blank=True, max_length=120, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'VS Users',
            },
        ),
    ]
