# Generated by Django 3.0.7 on 2020-08-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsusers',
            name='Contact_no',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
