# Generated by Django 3.0.7 on 2020-08-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_vsusers_other'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vsusers',
            old_name='Other',
            new_name='Other_Type',
        ),
    ]
