# Generated by Django 3.0.7 on 2020-08-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200815_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsusers',
            name='Site_Link',
            field=models.URLField(blank=True, max_length=120, null=True),
        ),
    ]
