# Generated by Django 3.0.7 on 2020-09-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awcuponcode',
            options={'verbose_name_plural': 'LS Coupon Code'},
        ),
    ]
