# Generated by Django 3.0.7 on 2020-08-06 09:40

from django.db import migrations, models
import django.utils.timezone
import project_control.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VsSystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Title', models.CharField(max_length=120)),
                ('Tag_Line', models.CharField(blank=True, max_length=120, null=True)),
                ('Logo', models.ImageField(upload_to=project_control.models.user_directory_path)),
                ('Favicon_Icon', models.ImageField(upload_to=project_control.models.user_directory_path_favicon)),
                ('No_of_videos_watch_befure_login', models.IntegerField(default=0, help_text='0 miens unlimited')),
                ('No_of_videos_watch_after_login', models.IntegerField(default=0, help_text='0 miens unlimited')),
                ('No_of_videos_uploaded_by_one_account', models.IntegerField(default=0, help_text='0 miens unlimited')),
                ('Promotional_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Promotional_Email_password', models.CharField(blank=True, max_length=120, null=True)),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'VS System Settings',
            },
        ),
    ]
