# Generated by Django 3.0.7 on 2020-08-06 09:40

import categorys_and_reatings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120, unique=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to=categorys_and_reatings.models.user_directory_path_category_image)),
                ('Slug', models.CharField(blank=True, max_length=120, null=True)),
                ('Status', models.BooleanField(default=True)),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Created_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_cate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'VS Category',
            },
        ),
        migrations.CreateModel(
            name='VsSubCategoryes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('Slug', models.CharField(blank=True, max_length=120, null=True)),
                ('Status', models.BooleanField(default=True)),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VsCategory_sub_cate', to='categorys_and_reatings.VsCategory')),
                ('Created_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_sub_cate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'VS Sub Categoryes',
            },
        ),
        migrations.CreateModel(
            name='VsReatingAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120, unique=True)),
                ('Slug', models.CharField(blank=True, max_length=120, null=True)),
                ('Status', models.BooleanField(default=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Reating_Range', models.IntegerField(default=0)),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Created_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_VsReatingAttribute', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'VS Reating Attribute',
            },
        ),
        migrations.CreateModel(
            name='VsConnectReatingWithCate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='VsCategory_connect', to='categorys_and_reatings.VsCategory')),
                ('Created_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_VsConnectReatingWithCate', to=settings.AUTH_USER_MODEL)),
                ('Readint_attribute', models.ManyToManyField(blank=True, related_name='VsReatingAttribute_connect', to='categorys_and_reatings.VsReatingAttribute')),
                ('Sub_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='VsSubCategoryes_connect', to='categorys_and_reatings.VsSubCategoryes')),
            ],
            options={
                'verbose_name_plural': 'Vs Attribute Connet With Categoryes',
            },
        ),
    ]
