# Generated by Django 3.0.7 on 2020-08-06 09:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VsPayPal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PayPal_Clientid', models.CharField(help_text='IF you add sendbox Client_id then PayPal work as sendbox and if you add Live client_id then PayPal work as Live.', max_length=500)),
                ('update_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name_plural': 'Vs PayPal',
            },
        ),
        migrations.CreateModel(
            name='VsSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_name', models.CharField(max_length=500)),
                ('Price', models.FloatField(default=0)),
                ('Free_trial', models.BooleanField(default=False, help_text='one month free trial for first user')),
                ('Upload_Video_limit', models.IntegerField(default=0)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Set_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'VS Subscription',
            },
        ),
        migrations.CreateModel(
            name='VsUserSubscriptionPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120)),
                ('Upload_Video_limit', models.IntegerField(default=0)),
                ('Buy_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Expayer_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Payment_status', models.BooleanField(default=False)),
                ('Active_status', models.BooleanField(default=False)),
                ('Amount', models.FloatField(default=0)),
                ('Payment_method', models.CharField(blank=True, max_length=500, null=True)),
                ('Transaction_id', models.CharField(blank=True, max_length=500, null=True)),
                ('Package_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_VsSubscription', to='subscription.VsSubscription')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_VsUserSubscriptionPayment', to='account.VsUsers')),
            ],
            options={
                'verbose_name_plural': 'VS User Subscription Payment',
            },
        ),
    ]
