# Generated by Django 3.0.7 on 2020-09-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_coupons', '0002_auto_20200917_0917'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsusersubscriptionpayment',
            name='Descount_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Coupon_code_VsSubscription', to='manage_coupons.AwCuponCode'),
        ),
    ]
