# Generated by Django 3.0.7 on 2020-09-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_vsusersubscriptionpayment_descount_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsusersubscriptionpayment',
            name='Amount_after_descount',
            field=models.FloatField(default=0),
        ),
    ]
