# Generated by Django 3.0.7 on 2020-08-06 09:40

from django.db import migrations, models
import manage_cms_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VsCmsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500, unique=True)),
                ('keyword', models.CharField(max_length=500, unique=True)),
                ('Background_Image', models.ImageField(blank=True, null=True, upload_to=manage_cms_page.models.user_directory_path_backgrount_image)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Page_content', models.TextField(blank=True, null=True)),
                ('set_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'VS CMS Page Content',
            },
        ),
    ]
